<a href="https://colab.research.google.com/github/tusharsuthar4828/DataScience_Assigments/blob/main/Naive_Bayes_SalaryData.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd

from sklearn.naive_bayes import MultinomialNB as MB
from sklearn.naive_bayes import GaussianNB as GB

In [2]:
! pip install naive-bayes

Collecting naive-bayes
  Downloading naive-bayes-0.1.1.tar.gz (1.8 kB)
Requirement already satisfied: scikit-learn>=0.15.2 in /usr/local/lib/python3.7/dist-packages (from naive-bayes) (1.0.2)
Requirement already satisfied: numpy>=1.9.0 in /usr/local/lib/python3.7/dist-packages (from naive-bayes) (1.21.5)
Requirement already satisfied: threadpoolctl>=2.0.0 in /usr/local/lib/python3.7/dist-packages (from scikit-learn>=0.15.2->naive-bayes) (3.1.0)
Requirement already satisfied: joblib>=0.11 in /usr/local/lib/python3.7/dist-packages (from scikit-learn>=0.15.2->naive-bayes) (1.1.0)
Requirement already satisfied: scipy>=1.1.0 in /usr/local/lib/python3.7/dist-packages (from scikit-learn>=0.15.2->naive-bayes) (1.4.1)
Building wheels for collected packages: naive-bayes
  Building wheel for naive-bayes (setup.py) ... done
  Created wheel for naive-bayes: filename=naive_bayes-0.1.1-py3-none-any.whl size=2187 sha256=9d85b0b2c54166555cf5bf74720ab10c30d7bbf338b455f45d5d1a16eb22e8fe
  Stored in directory: /root/.cache/pip/wheels/52/47/13/1923f8fd67eb6d20f9d06a5c81ab3dc427126de6709c03ce88
Successfully built naive-bayes
Installing collected packages: naive-bayes
Successfully installed naive-bayes-0.1.1

In [3]:
train = pd.read_csv('/content/SalaryData_Train.csv')
test = pd.read_csv('/content/SalaryData_Test.csv')

In [4]:
#copying the data
df1 = train.copy()
df2 = test.copy()

In [5]:
df1.head()

   age          workclass   education  ...  hoursperweek          native  Salary
0   39          State-gov   Bachelors  ...            40   United-States   <=50K
1   50   Self-emp-not-inc   Bachelors  ...            13   United-States   <=50K
2   38            Private     HS-grad  ...            40   United-States   <=50K
3   53            Private        11th  ...            40   United-States   <=50K
4   28            Private   Bachelors  ...            40            Cuba   <=50K

[5 rows x 14 columns]

In [6]:
df2.head()

   age   workclass      education  ...  hoursperweek          native  Salary
0   25     Private           11th  ...            40   United-States   <=50K
1   38     Private        HS-grad  ...            50   United-States   <=50K
2   28   Local-gov     Assoc-acdm  ...            40   United-States    >50K
3   44     Private   Some-college  ...            40   United-States    >50K
4   34     Private           10th  ...            30   United-States   <=50K

[5 rows x 14 columns]

In [7]:
df1.isnull().sum()

age              0
workclass        0
education        0
educationno      0
maritalstatus    0
occupation       0
relationship     0
race             0
sex              0
capitalgain      0
capitalloss      0
hoursperweek     0
native           0
Salary           0
dtype: int64

In [8]:
df2.isnull().sum()

age              0
workclass        0
education        0
educationno      0
maritalstatus    0
occupation       0
relationship     0
race             0
sex              0
capitalgain      0
capitalloss      0
hoursperweek     0
native           0
Salary           0
dtype: int64

In [9]:
#ONE HOT ENCODING
tr1 = df1.iloc[:,0:13]

tr1 = pd.get_dummies(tr1)
tr1

       age  educationno  ...  native_ Vietnam  native_ Yugoslavia
0       39           13  ...                0                   0
1       50           13  ...                0                   0
2       38            9  ...                0                   0
3       53            7  ...                0                   0
4       28           13  ...                0                   0
...    ...          ...  ...              ...                 ...
30156   27           12  ...                0                   0
30157   40            9  ...                0                   0
30158   58            9  ...                0                   0
30159   22            9  ...                0                   0
30160   52            9  ...                0                   0

[30161 rows x 102 columns]

In [10]:
te1 = test.iloc[:,0:13]

te1 = pd.get_dummies(te1)
te1

       age  educationno  ...  native_ Vietnam  native_ Yugoslavia
0       25            7  ...                0                   0
1       38            9  ...                0                   0
2       28           12  ...                0                   0
3       44           10  ...                0                   0
4       34            6  ...                0                   0
...    ...          ...  ...              ...                 ...
15055   33           13  ...                0                   0
15056   39           13  ...                0                   0
15057   38           13  ...                0                   0
15058   44           13  ...                0                   0
15059   35           13  ...                0                   0

[15060 rows x 102 columns]

In [11]:
#train data concat
finaltrain = pd.concat([tr1, df1['Salary']],axis=1)
finaltrain

       age  educationno  ...  native_ Yugoslavia  Salary
0       39           13  ...                   0   <=50K
1       50           13  ...                   0   <=50K
2       38            9  ...                   0   <=50K
3       53            7  ...                   0   <=50K
4       28           13  ...                   0   <=50K
...    ...          ...  ...                 ...     ...
30156   27           12  ...                   0   <=50K
30157   40            9  ...                   0    >50K
30158   58            9  ...                   0   <=50K
30159   22            9  ...                   0   <=50K
30160   52            9  ...                   0    >50K

[30161 rows x 103 columns]

In [12]:
#test data concat
finaltest = pd.concat([te1, df2['Salary']],axis=1)
finaltest

       age  educationno  ...  native_ Yugoslavia  Salary
0       25            7  ...                   0   <=50K
1       38            9  ...                   0   <=50K
2       28           12  ...                   0    >50K
3       44           10  ...                   0    >50K
4       34            6  ...                   0   <=50K
...    ...          ...  ...                 ...     ...
15055   33           13  ...                   0   <=50K
15056   39           13  ...                   0   <=50K
15057   38           13  ...                   0   <=50K
15058   44           13  ...                   0   <=50K
15059   35           13  ...                   0    >50K

[15060 rows x 103 columns]

In [13]:
# Finaltrain data
X = finaltrain.values[:,0:102]
Y = finaltrain.values[:,102]

#Finaltest data
x = finaltest.values[:,0:102]
y = finaltest.values[:,102]

In [15]:
#Naive Bayes Model
#Multinomial Naive Bayes

In [16]:
classifier_mb = MB()
classifier_mb.fit(X,Y)
train_pred_m = classifier_mb.predict(X)
accuracy_train_m = np.mean(train_pred_m==Y)

In [17]:
test_pred_m = classifier_mb.predict(x)
accuracy_test_m = np.mean(test_pred_m==y)

In [18]:
print('Training accuracy is:',accuracy_train_m,'\n','Testing accuracy is:',accuracy_test_m)

Training accuracy is: 0.7729186698053778
 Testing accuracy is: 0.7749667994687915

In [19]:
#Gaussian Naive Bayes

In [20]:
classifier_gb = GB()
classifier_gb.fit(X,Y) 
# we need to convert tfidf into array format which is compatible for gaussian naive bayes
train_pred_g = classifier_gb.predict(X)
accuracy_train_g = np.mean(train_pred_g==Y)

In [21]:
test_pred_g = classifier_gb.predict(x)
accuracy_test_g = np.mean(test_pred_g==y)

In [22]:
accuracy_test_g

0.8029216467463479